services:
  - type: web
    name: guardiao-auto-bot
    env: python
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: |
      pip install -U pip
      pip install -r requirements.txt
    startCommand: uvicorn webhook_app:app --host 0.0.0.0 --port $PORT

    envVars:
      # versão do python usada pelo Render
      - key: PYTHON_VERSION
        value: 3.11.9

      # === SEGREDOS: defina pelo Dashboard do Render (ou via CLI) ===
      # NUNCA comite o token do bot nem o webhook token no git.
      - key: TG_BOT_TOKEN
        sync: false
      - key: WEBHOOK_TOKEN
        sync: false

      # === Canais (podem ficar no YAML) ===
      # Se quiser filtrar a origem, coloque o canal fonte; vazio aceita de qualquer chat.
      - key: SOURCE_CHANNEL
        value: ""          # ex.: "-1002810508717"
      - key: TARGET_CHANNEL
        value: "-1003052132833"   # substitua pelo seu canal alvo

      # === Opções úteis (podem manter os defaults) ===
      - key: SHOW_DEBUG
        value: "True"      # "False" para não enviar mensagens DEBUG
      - key: OBS_TIMEOUT_SEC
        value: "420"
      - key: DEDUP_WINDOW_SEC
        value: "40"

      # (opcionais) controles finos — já temos Auto-Tuner interno:
      # - key: CTL_MIN_CONF; value: "0.72"
      # - key: CTL_EPSILON;  value: "0.08"
      # - key: SLATE_K;      value: "3"
      # - key: SLATE_GAP_MAX; value: "0.15"
      # - key: SLATE_MINCONF; value: "0.18"
      # - key: DIVERSITY_LASTK; value: "30"
      # - key: DIVERSITY_MAX_SHARE; value: "0.36"
      # - key: DIVERSITY_MAX_SAME; value: "2"
      # - key: ANTIENTROPY_PUSH; value: "0.12"
      # - key: CLASS_COOLDOWN_REPS; value: "2"
      # - key: CLASS_COOLDOWN_DELTA; value: "0.06"
